# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autonomous_msg/VehicleOutputs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autonomous_msg.msg

class VehicleOutputs(genpy.Message):
  _md5sum = "1f3e123ab591600bc0713eeba94ade0a"
  _type = "autonomous_msg/VehicleOutputs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """VehicleOutput[] vehicleOuputs
================================================================================
MSG: autonomous_msg/VehicleOutput
string id 
float64 x
float64 y
float64 yaw
float64 velocity
float64 length
float64 width"""
  __slots__ = ['vehicleOuputs']
  _slot_types = ['autonomous_msg/VehicleOutput[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vehicleOuputs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleOutputs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vehicleOuputs is None:
        self.vehicleOuputs = []
    else:
      self.vehicleOuputs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.vehicleOuputs)
      buff.write(_struct_I.pack(length))
      for val1 in self.vehicleOuputs:
        _x = val1.id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_6d().pack(_x.x, _x.y, _x.yaw, _x.velocity, _x.length, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vehicleOuputs is None:
        self.vehicleOuputs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.vehicleOuputs = []
      for i in range(0, length):
        val1 = autonomous_msg.msg.VehicleOutput()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.id = str[start:end]
        _x = val1
        start = end
        end += 48
        (_x.x, _x.y, _x.yaw, _x.velocity, _x.length, _x.width,) = _get_struct_6d().unpack(str[start:end])
        self.vehicleOuputs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.vehicleOuputs)
      buff.write(_struct_I.pack(length))
      for val1 in self.vehicleOuputs:
        _x = val1.id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_6d().pack(_x.x, _x.y, _x.yaw, _x.velocity, _x.length, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vehicleOuputs is None:
        self.vehicleOuputs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.vehicleOuputs = []
      for i in range(0, length):
        val1 = autonomous_msg.msg.VehicleOutput()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.id = str[start:end]
        _x = val1
        start = end
        end += 48
        (_x.x, _x.y, _x.yaw, _x.velocity, _x.length, _x.width,) = _get_struct_6d().unpack(str[start:end])
        self.vehicleOuputs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
