// Generated by gencpp from file autonomous_msg/EnvironmentDetected.msg
// DO NOT EDIT!


#ifndef AUTONOMOUS_MSG_MESSAGE_ENVIRONMENTDETECTED_H
#define AUTONOMOUS_MSG_MESSAGE_ENVIRONMENTDETECTED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autonomous_msg
{
template <class ContainerAllocator>
struct EnvironmentDetected_
{
  typedef EnvironmentDetected_<ContainerAllocator> Type;

  EnvironmentDetected_()
    : ice_param(0.0)
    , ice_mode()  {
    }
  EnvironmentDetected_(const ContainerAllocator& _alloc)
    : ice_param(0.0)
    , ice_mode(_alloc)  {
  (void)_alloc;
    }



   typedef double _ice_param_type;
  _ice_param_type ice_param;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ice_mode_type;
  _ice_mode_type ice_mode;





  typedef boost::shared_ptr< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> const> ConstPtr;

}; // struct EnvironmentDetected_

typedef ::autonomous_msg::EnvironmentDetected_<std::allocator<void> > EnvironmentDetected;

typedef boost::shared_ptr< ::autonomous_msg::EnvironmentDetected > EnvironmentDetectedPtr;
typedef boost::shared_ptr< ::autonomous_msg::EnvironmentDetected const> EnvironmentDetectedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator1> & lhs, const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator2> & rhs)
{
  return lhs.ice_param == rhs.ice_param &&
    lhs.ice_mode == rhs.ice_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator1> & lhs, const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autonomous_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57850e5a040808185fbe00e153e12c75";
  }

  static const char* value(const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57850e5a04080818ULL;
  static const uint64_t static_value2 = 0x5fbe00e153e12c75ULL;
};

template<class ContainerAllocator>
struct DataType< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autonomous_msg/EnvironmentDetected";
  }

  static const char* value(const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ice_param\n"
"string ice_mode\n"
;
  }

  static const char* value(const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ice_param);
      stream.next(m.ice_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnvironmentDetected_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autonomous_msg::EnvironmentDetected_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autonomous_msg::EnvironmentDetected_<ContainerAllocator>& v)
  {
    s << indent << "ice_param: ";
    Printer<double>::stream(s, indent + "  ", v.ice_param);
    s << indent << "ice_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ice_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTONOMOUS_MSG_MESSAGE_ENVIRONMENTDETECTED_H
