// Generated by gencpp from file autonomous_msg/LanePointData.msg
// DO NOT EDIT!


#ifndef AUTONOMOUS_MSG_MESSAGE_LANEPOINTDATA_H
#define AUTONOMOUS_MSG_MESSAGE_LANEPOINTDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <autonomous_msg/PointWithArclength.h>

namespace autonomous_msg
{
template <class ContainerAllocator>
struct LanePointData_
{
  typedef LanePointData_<ContainerAllocator> Type;

  LanePointData_()
    : frame_id()
    , id()
    , point()  {
    }
  LanePointData_(const ContainerAllocator& _alloc)
    : frame_id(_alloc)
    , id(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_type;
  _id_type id;

   typedef std::vector< ::autonomous_msg::PointWithArclength_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::autonomous_msg::PointWithArclength_<ContainerAllocator> >> _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::autonomous_msg::LanePointData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autonomous_msg::LanePointData_<ContainerAllocator> const> ConstPtr;

}; // struct LanePointData_

typedef ::autonomous_msg::LanePointData_<std::allocator<void> > LanePointData;

typedef boost::shared_ptr< ::autonomous_msg::LanePointData > LanePointDataPtr;
typedef boost::shared_ptr< ::autonomous_msg::LanePointData const> LanePointDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autonomous_msg::LanePointData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autonomous_msg::LanePointData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autonomous_msg::LanePointData_<ContainerAllocator1> & lhs, const ::autonomous_msg::LanePointData_<ContainerAllocator2> & rhs)
{
  return lhs.frame_id == rhs.frame_id &&
    lhs.id == rhs.id &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autonomous_msg::LanePointData_<ContainerAllocator1> & lhs, const ::autonomous_msg::LanePointData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autonomous_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autonomous_msg::LanePointData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autonomous_msg::LanePointData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_msg::LanePointData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_msg::LanePointData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_msg::LanePointData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_msg::LanePointData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autonomous_msg::LanePointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcc833df10bd61adf00504adcdbf2635";
  }

  static const char* value(const ::autonomous_msg::LanePointData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcc833df10bd61adULL;
  static const uint64_t static_value2 = 0xf00504adcdbf2635ULL;
};

template<class ContainerAllocator>
struct DataType< ::autonomous_msg::LanePointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autonomous_msg/LanePointData";
  }

  static const char* value(const ::autonomous_msg::LanePointData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autonomous_msg::LanePointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string frame_id\n"
"string id \n"
"autonomous_msg/PointWithArclength[] point\n"
"================================================================================\n"
"MSG: autonomous_msg/PointWithArclength\n"
"float64 x\n"
"float64 y\n"
"float64 arclength\n"
;
  }

  static const char* value(const ::autonomous_msg::LanePointData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autonomous_msg::LanePointData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.id);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LanePointData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autonomous_msg::LanePointData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autonomous_msg::LanePointData_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id);
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::autonomous_msg::PointWithArclength_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTONOMOUS_MSG_MESSAGE_LANEPOINTDATA_H
