// Generated by gencpp from file autonomous_msg/PolyfitLaneDataArray.msg
// DO NOT EDIT!


#ifndef AUTONOMOUS_MSG_MESSAGE_POLYFITLANEDATAARRAY_H
#define AUTONOMOUS_MSG_MESSAGE_POLYFITLANEDATAARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <autonomous_msg/PolyfitLaneData.h>

namespace autonomous_msg
{
template <class ContainerAllocator>
struct PolyfitLaneDataArray_
{
  typedef PolyfitLaneDataArray_<ContainerAllocator> Type;

  PolyfitLaneDataArray_()
    : frame_id()
    , polyfitLanes()  {
    }
  PolyfitLaneDataArray_(const ContainerAllocator& _alloc)
    : frame_id(_alloc)
    , polyfitLanes(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef std::vector< ::autonomous_msg::PolyfitLaneData_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::autonomous_msg::PolyfitLaneData_<ContainerAllocator> >> _polyfitLanes_type;
  _polyfitLanes_type polyfitLanes;





  typedef boost::shared_ptr< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> const> ConstPtr;

}; // struct PolyfitLaneDataArray_

typedef ::autonomous_msg::PolyfitLaneDataArray_<std::allocator<void> > PolyfitLaneDataArray;

typedef boost::shared_ptr< ::autonomous_msg::PolyfitLaneDataArray > PolyfitLaneDataArrayPtr;
typedef boost::shared_ptr< ::autonomous_msg::PolyfitLaneDataArray const> PolyfitLaneDataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator1> & lhs, const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator2> & rhs)
{
  return lhs.frame_id == rhs.frame_id &&
    lhs.polyfitLanes == rhs.polyfitLanes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator1> & lhs, const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autonomous_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c4f872af1e86d670a3cbaed9d3c5647";
  }

  static const char* value(const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c4f872af1e86d67ULL;
  static const uint64_t static_value2 = 0x0a3cbaed9d3c5647ULL;
};

template<class ContainerAllocator>
struct DataType< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autonomous_msg/PolyfitLaneDataArray";
  }

  static const char* value(const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string frame_id\n"
"PolyfitLaneData[] polyfitLanes\n"
"================================================================================\n"
"MSG: autonomous_msg/PolyfitLaneData\n"
"string frame_id\n"
"string id \n"
"float64 a0\n"
"float64 a1\n"
"float64 a2\n"
"float64 a3\n"
;
  }

  static const char* value(const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.polyfitLanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolyfitLaneDataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autonomous_msg::PolyfitLaneDataArray_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "polyfitLanes[]" << std::endl;
    for (size_t i = 0; i < v.polyfitLanes.size(); ++i)
    {
      s << indent << "  polyfitLanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::autonomous_msg::PolyfitLaneData_<ContainerAllocator> >::stream(s, indent + "    ", v.polyfitLanes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTONOMOUS_MSG_MESSAGE_POLYFITLANEDATAARRAY_H
